
spring:
  datasource:
    password: serverdbp
    username: serverdbu
    url: jdbc:postgresql://localhost:5432/serverdb

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true
  output:
    ansi:
      enabled: ALWAYS
